# compose 파일 버전
version: '3'
services:
  # 서비스 명
  db:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: postgres
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - '5432:5432'
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: api_test
      POSTGRES_PASSWORD: sangdojoong
    # 볼륨 설정
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    networks:
      - backend

  fastapi:
    image: sangdo_fastapi:0.2
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - '8080:8080'
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/code/app
      - /home/ubuntu/uploads:/uploads
    networks:
      - backend
    env_file:
      - secret.env

networks:
  backend:
    driver: bridge
